<robot>

<macro name="cylinder_inertia" params="m r h">
  <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
    iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
    izz="${m*r*r/2}"/>
</macro>

<macro name="box_inertia" params="m x y z">
  <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
    iyy="${m*(x*x+z*z)/12}" iyz = "0"
    izz="${m*(x*x+z*z)/12}"/>
</macro>

<macro name="sphere_inertia" params="m r">
  <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
    iyy="${2*m*r*r/5}" iyz = "0"
    izz="${2*m*r*r/5}"/>
</macro>

<macro name="wheel" params="n1234 fb lr">

<link name="wheel_${n1234}">
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <cylinder length="${length_wheel}" radius="${radius_wheel}"/>
    </geometry>
  </visual>

    <inertial>
      <mass value="0.06" />
      <cylinder_inertia m="0.06" r="${radius_wheel}" h="${length_wheel}"/>
  </inertial>
</link>

<gazebo reference="wheel_${n1234}">
  <mu1 value="100000"/>
  <mu2 value="100000"/>
  <kp  value="100000000000.0" />
  <kd  value="1.0" />
  <fdir1 value="0 1 0"/>
</gazebo>


<joint name="base_to_wheel${n1234}" type="continuous">
  <parent link="chassis"/>
  <child link="wheel_${n1234}"/>
  <origin xyz="${fb*chassisLength*0.5} ${lr*wheelPos} ${radius_wheel}" rpy="1.5707 0 0" />
  <axis xyz="0 0 -1" />
</joint>
</macro>
</robot>
